apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ljo7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-ljo7@sha256:ad84dbed28490ebdeb141cb1d36e534c7feab0c0d77cef1ab27816e3c7e1d885
        name: my-nodejs
        resources: {}
status: {}
